# Generated by Django 2.2.16 on 2021-05-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0002_subscriptiontable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionTable',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='active',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user_membership',
        ),
        migrations.AddField(
            model_name='subscription',
            name='annually_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='monthly_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
