# Generated by Django 2.2.16 on 2021-05-09 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0007_auto_20210509_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiontable',
            name='created',
        ),
        migrations.RemoveField(
            model_name='subscriptiontable',
            name='modified',
        ),
    ]
