# Generated by Django 2.2.16 on 2021-05-09 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0008_auto_20210509_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontable',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiontable',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiontable',
            name='user_membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_service.UserMembership'),
        ),
    ]
