# Generated by Django 2.2.16 on 2021-05-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0009_auto_20210509_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontable',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
