# Generated by Django 2.2.16 on 2021-05-09 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0011_auto_20210509_1237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMembership',
        ),
    ]
