# Generated by Django 2.2.16 on 2021-05-09 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0012_delete_usermembership'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMembership1',
            new_name='UserMembership',
        ),
    ]
