# Generated by Django 2.2.16 on 2021-05-09 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0013_auto_20210509_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionfeatures',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_service.Subscription'),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_service.Subscription'),
        ),
        migrations.DeleteModel(
            name='SubscriptionTable',
        ),
    ]
