# Generated by Django 2.2.16 on 2021-05-09 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0016_profile_subscription_valid_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subscription_valid_date',
        ),
    ]
