# Generated by Django 2.2.16 on 2021-05-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0017_remove_profile_subscription_valid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription_valid_date1',
            field=models.DateField(blank=True, null=True, verbose_name='%m-%y-%d'),
        ),
    ]
