# Generated by Django 2.2.16 on 2021-05-09 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0018_profile_subscription_valid_date1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription_valid_date1',
        ),
    ]
