# Generated by Django 2.2.16 on 2021-05-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0019_auto_20210509_1402'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
