# Generated by Django 2.2.16 on 2021-05-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0023_testresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
