# Generated by Django 2.2.16 on 2021-05-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0025_auto_20210525_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='created_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='next_billing_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
