# Generated by Django 2.2.16 on 2021-05-25 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0026_auto_20210525_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionfeatures',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_service.Subscription'),
        ),
    ]
