# Generated by Django 2.2.16 on 2021-05-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0027_auto_20210525_2233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionFeatures',
        ),
    ]
