# Generated by Django 2.2.16 on 2021-05-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0029_subscriptionfeatures'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionHistory',
        ),
    ]
