# Generated by Django 2.2.16 on 2021-05-26 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0031_subscriptionhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionhistory',
            old_name='tracking_id',
            new_name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='subscriptionhistory',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='subscriptionhistory',
            name='type',
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='created_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='membership_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_service.Membership'),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
