# Generated by Django 2.2.16 on 2021-05-26 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0033_auto_20210526_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_service.Membership'),
        ),
    ]
