# Generated by Django 2.2.16 on 2021-05-26 07:17

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0034_auto_20210526_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.CharField, to='user_service.Membership'),
        ),
    ]
