# Generated by Django 2.2.16 on 2021-05-26 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0035_auto_20210526_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
