# Generated by Django 2.2.16 on 2021-05-26 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0036_auto_20210526_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionhistory',
            name='user',
        ),
    ]
