# Generated by Django 2.2.16 on 2021-06-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0039_auto_20210527_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
