# Generated by Django 2.2.16 on 2021-06-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0041_auto_20210603_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.AddField(
            model_name='subscription',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
