# Generated by Django 2.2.16 on 2021-06-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0044_auto_20210603_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='next_billing_date',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
    ]
