# Generated by Django 2.2.16 on 2021-06-20 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0046_auto_20210619_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='next_billing_date',
        ),
    ]
