# Generated by Django 2.2.16 on 2021-06-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0047_remove_user_next_billing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('none', 'Other')], default='male', max_length=50),
        ),
    ]
