# Generated by Django 2.2.16 on 2021-03-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_services', '0003_auto_20210329_0705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='directory',
            old_name='user_id',
            new_name='user',
        ),
    ]
