# Generated by Django 2.2.16 on 2021-03-31 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_services', '0004_auto_20210329_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directoryfavorite',
            old_name='directory_id',
            new_name='directory',
        ),
        migrations.RenameField(
            model_name='directoryfavorite',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='directoryhistory',
            old_name='directory_id',
            new_name='directory',
        ),
        migrations.RenameField(
            model_name='directoryhistory',
            old_name='user_id',
            new_name='user',
        ),
    ]
