# Generated by Django 2.2.16 on 2021-03-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_services', '0005_auto_20210331_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='source',
            field=models.CharField(choices=[('1', 'Api'), ('2', 'Manual'), ('annually', 'Annually')], default='Api', max_length=255),
        ),
    ]
