# Generated by Django 2.2.16 on 2021-03-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_services', '0006_auto_20210331_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoryfavorite',
            name='like',
            field=models.CharField(choices=[(1, 'Like'), (2, 'Unlike')], default='Like', max_length=255),
        ),
        migrations.AlterField(
            model_name='directory',
            name='source',
            field=models.CharField(choices=[(1, 'Api'), (2, 'Manual')], default='Api', max_length=255),
        ),
    ]
