# Generated by Django 2.2.16 on 2021-04-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_services', '0007_auto_20210331_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directoryfavorite',
            name='like',
            field=models.CharField(choices=[(1, 'Like'), (0, 'Unlike')], default='Like', max_length=255),
        ),
    ]
