# Generated by Django 2.2.16 on 2021-04-02 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_services', '0008_auto_20210401_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directoryfavorite',
            name='like',
        ),
    ]
