# Generated by Django 2.2.16 on 2021-04-05 07:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news_services', '0009_remove_directoryfavorite_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryTiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('day', models.CharField(choices=[('Monday', 1), ('Tuesday', 2), ('Wednesday', 3), ('Thursday', 4), ('Friday', 5), ('Saturday', 6), ('Sunday', 7)], max_length=255)),
                ('opening_date', models.TimeField(blank=True, null=True)),
                ('closing_date', models.TimeField(blank=True, null=True)),
                ('directory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_services.Directory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
