# Generated by Django 2.2.16 on 2021-04-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_services', '0010_directorytiming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='email',
        ),
    ]
