# Generated by Django 2.2.16 on 2021-04-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_services', '0011_remove_directory_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorytiming',
            name='day',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=255),
        ),
    ]
