# Generated by Django 2.2.16 on 2021-04-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_services', '0012_auto_20210405_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='phone_no',
            field=models.CharField(max_length=255),
        ),
    ]
