# Generated by Django 2.2.16 on 2021-04-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_services', '0013_auto_20210406_0439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directory',
            old_name='name',
            new_name='area_code',
        ),
        migrations.AddField(
            model_name='directory',
            name='comapany_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='directory',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='directory',
            name='employee_designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='directory',
            name='employee_designation_code',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='directory',
            name='employee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='directory',
            name='employee_phone_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='directory',
            name='fax_no',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='directory',
            name='tool_free_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='directory',
            name='year_founded',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
