# Generated by Django 2.2.16 on 2021-04-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_services', '0016_auto_20210406_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='about',
            field=models.SlugField(max_length=255),
        ),
    ]
