# Generated by Django 2.2.16 on 2021-04-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_services', '0020_auto_20210407_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='comapany_name',
        ),
        migrations.AddField(
            model_name='directory',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
