# Generated by Django 2.2.16 on 2021-04-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_services', '0021_auto_20210414_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='is_public',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
