# Generated by Django 2.2.16 on 2021-04-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_services', '0024_auto_20210419_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='directory',
            name='latitude',
            field=models.FloatField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='directory',
            name='longitude',
            field=models.FloatField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='directory',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='directory',
            name='street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='directory',
            name='zip',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
