# Generated by Django 2.2.16 on 2021-04-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_services', '0025_auto_20210419_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='area_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
