# Generated by Django 2.2.16 on 2021-04-21 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_services', '0028_auto_20210421_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directoryhistory',
            name='directory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DirectoryHistory.directory +', to='news_services.Directory'),
        ),
    ]
