# Generated by Django 2.2.16 on 2021-04-21 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_services', '0030_auto_20210421_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directoryfavorite',
            name='directory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directory', to='news_services.Directory'),
        ),
    ]
