# Generated by Django 2.2.16 on 2021-04-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_services', '0032_auto_20210421_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directoryfavorite',
            name='directory',
            field=models.ManyToManyField(blank=True, related_name='directory', to='news_services.Directory'),
        ),
    ]
