# Generated by Django 2.2.16 on 2021-04-21 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_services', '0033_auto_20210421_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directoryfavorite',
            name='directory',
        ),
        migrations.AddField(
            model_name='directoryfavorite',
            name='directory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_services.Directory'),
        ),
    ]
