# Generated by Django 2.2.16 on 2021-04-21 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_services', '0034_auto_20210421_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directoryhistory',
            name='directory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_services.Directory'),
        ),
    ]
