# Generated by Django 2.2.16 on 2021-04-27 04:48

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news_services', '0035_auto_20210421_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentApiHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='directory',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='directory',
            name='area_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='directory',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='directory',
            name='is_public',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='directory',
            name='latitude',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='directory',
            name='longitude',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='directory',
            name='phone_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='directory',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='directory',
            name='street_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='directory',
            name='zip',
            field=models.CharField(max_length=100),
        ),
    ]
