# Generated by Django 2.2.16 on 2021-06-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_services', '0037_auto_20210503_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='directory',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='directory',
            name='latitude',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='directory',
            name='longitude',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='directory',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='directory',
            name='zip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
