# Generated by Django 2.2.16 on 2021-06-03 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_services', '0038_auto_20210602_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directory_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
