# Generated by Django 2.2.16 on 2021-06-07 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_services', '0039_auto_20210603_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorytiming',
            name='directory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directory_timing', to='news_services.Directory'),
        ),
    ]
