# Generated by Django 2.2.16 on 2021-07-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_services', '0043_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
